"""initial_schema

Revision ID: 3a133926c589
Revises: 
Create Date: 2026-09-09 09:45:01.667710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a133926c589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('related_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_type'), 'alerts', ['type'], unique=False)
    op.create_table('device_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('criticality_weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('baselines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_group_id', sa.Uuid(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baselines_is_active'), 'baselines', ['is_active'], unique=False)
    op.create_table('change_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_ref', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('device_group_id', sa.Uuid(), nullable=True),
    sa.Column('key_path_scope', sa.String(length=255), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['device_group_id'], ['device_groups.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_ref')
    )
    op.create_table('configuration_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('raw_config', sa.Text(), nullable=False),
    sa.Column('normalized_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('collection_method', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuration_snapshots_collected_at'), 'configuration_snapshots', ['collected_at'], unique=False)
    op.create_index(op.f('ix_configuration_snapshots_device_id'), 'configuration_snapshots', ['device_id'], unique=False)
    op.create_index('ix_configuration_snapshots_normalized_json', 'configuration_snapshots', ['normalized_json'], unique=False, postgresql_using='gin')
    op.create_table('device_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('username_enc', sa.LargeBinary(), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('baseline_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('baseline_id', sa.Uuid(), nullable=False),
    sa.Column('key_path', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('severity_weight', sa.Integer(), nullable=False),
    sa.Column('hard_compliance', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('baseline_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('matched_ticket_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['baseline_id'], ['baselines.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['matched_ticket_id'], ['change_tickets.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['configuration_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_events_detected_at'), 'drift_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_drift_events_device_id'), 'drift_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_drift_events_label'), 'drift_events', ['label'], unique=False)
    op.create_index(op.f('ix_drift_events_risk_score'), 'drift_events', ['risk_score'], unique=False)
    op.create_table('drift_details',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drift_event_id', sa.Uuid(), nullable=False),
    sa.Column('key_path', sa.String(length=255), nullable=False),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('actual_value', sa.Text(), nullable=True),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['drift_event_id'], ['drift_events.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['baseline_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_details_drift_event_id'), 'drift_details', ['drift_event_id'], unique=False)
    op.create_table('remediation_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('drift_event_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_commands', app.models.types.StringArrayType(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['drift_event_id'], ['drift_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_plan_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remediation_plan_id')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('remediation_plan_id', sa.Uuid(), nullable=False),
    sa.Column('executed_commands', app.models.types.StringArrayType(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('verification_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ),
    sa.ForeignKeyConstraint(['verification_snapshot_id'], ['configuration_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('config_blob', sa.Text(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('taken_before_action_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['taken_before_action_id'], ['remediation_actions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_device_id'), 'backups', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backups_device_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_table('remediation_actions')
    op.drop_table('approvals')
    op.drop_table('remediation_plans')
    op.drop_index(op.f('ix_drift_details_drift_event_id'), table_name='drift_details')
    op.drop_table('drift_details')
    op.drop_index(op.f('ix_drift_events_risk_score'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_label'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_device_id'), table_name='drift_events')
    op.drop_index(op.f('ix_drift_events_detected_at'), table_name='drift_events')
    op.drop_table('drift_events')
    op.drop_table('baseline_rules')
    op.drop_table('device_credentials')
    op.drop_index('ix_configuration_snapshots_normalized_json', table_name='configuration_snapshots', postgresql_using='gin')
    op.drop_index(op.f('ix_configuration_snapshots_device_id'), table_name='configuration_snapshots')
    op.drop_index(op.f('ix_configuration_snapshots_collected_at'), table_name='configuration_snapshots')
    op.drop_table('configuration_snapshots')
    op.drop_table('change_tickets')
    op.drop_index(op.f('ix_baselines_is_active'), table_name='baselines')
    op.drop_table('baselines')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('roles')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_alerts_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
