"""add underlying_severity and make baseline_id nullable on drift_events

Revision ID: c708d9c9e82c
Revises: d0933636435e
Create Date: 2026-09-09 14:50:09.162667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c708d9c9e82c'
down_revision: Union[str, None] = 'd0933636435e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drift_events', sa.Column('underlying_severity', sa.Integer(), nullable=True))
    op.alter_column('drift_events', 'baseline_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drift_events', 'baseline_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('drift_events', 'underlying_severity')
    # ### end Alembic commands ###
