"""add description to baseline_rules

Revision ID: d0933636435e
Revises: d80d570ddfe3
Create Date: 2026-09-09 11:47:45.969043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0933636435e'
down_revision: Union[str, None] = 'd80d570ddfe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baseline_rules', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baseline_rules', 'description')
    # ### end Alembic commands ###
