"""add status to configuration_snapshots

Revision ID: d80d570ddfe3
Revises: 3a133926c589
Create Date: 2026-09-09 10:44:39.281428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80d570ddfe3'
down_revision: Union[str, None] = '3a133926c589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('configuration_snapshots', sa.Column('status', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuration_snapshots', 'status')
    # ### end Alembic commands ###
