import React from 'react';
import { CheckSquare, ShieldCheck, Terminal } from 'lucide-react';
import { Link } from 'react-router-dom';

export const Remediation: React.FC = () => {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Remediation Engine</h2>
          <p className="text-sm text-slate-500">Jinja2 template-generated CLI commands gated behind strict approvals and automated rollback.</p>
        </div>
        <Link
          to="/approvals"
          className="inline-flex items-center gap-1.5 px-4 py-2 bg-emerald-600 hover:bg-emerald-500 text-white rounded-lg text-sm font-medium transition-colors"
        >
          <CheckSquare className="h-4 w-4" />
          <span>Go to Approval Queue</span>
        </Link>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm p-6 space-y-4">
        <div className="flex items-center gap-3 p-3 bg-amber-50 border border-amber-200 rounded-lg text-amber-800 text-sm">
          <ShieldCheck className="h-5 w-5 text-amber-600 shrink-0" />
          <div>
            <span className="font-semibold">Remediation Guardrail: </span>
            No free-text commands allowed. All CLI commands are strictly rendered from predefined Jinja2 templates.
          </div>
        </div>

        <div className="space-y-2">
          <h3 className="font-semibold text-slate-800 text-sm flex items-center gap-2">
            <Terminal className="h-4 w-4 text-sky-600" />
            <span>Sample Proposed Commands Preview</span>
          </h3>
          <pre className="p-4 bg-slate-900 text-emerald-400 font-mono text-xs rounded-lg overflow-x-auto">
{`! Generated by Jinja2 Template: line_vty_ssh.j2
configure terminal
line vty 0 4
 transport input ssh
end
write memory`}
          </pre>
        </div>
      </div>
    </div>
  );
};
